### ISSUE TITLE
Input files for the program

### ISSUE THREAD

**Issue by lakromah** [obsmax/srfpython#1]
I have run the contents of the tutorial in ipython and it seems to work fine. Where do I input my cross correlated files and other parameters like station coordinates in order to calculate the dispersion curves. It is not very clear what to do after the tutorial.

**Comment by obsmax** [comment]
Hi, 

The input of this program is not the noise correlation functions.
You have quite a lot of things to do first : 1/ measuring the dispersion curves between all stations, 
2/ regionalize the surface wave velocity for each period and 3/ extract a dispersion curve at each location in your model.

Once you have done all of that, you can store the dispersion curves into surf96 files and intput it to this program as shown in the tutorials.

Good luck,

Max

**Comment by lakromah** [comment]
Hi Max

Thank you for your response. i have now decided to use amb_noise_noise tools and it is going well since have not gotten any errors so far. i am running  a code called "noise.py" for pre-processing, cross correlation and dispersion curves extraction. However, the code does not say where to input my station codes, coordinates, interstation distances etc. Where can I input those and when running the code what is the order of the arguments after python3 noise.py ...?

The link is as follows:https://github.com/ekaestle/amb_noise_tools.

Looking forward to your response
Regards
Linda

**Comment by obsmax** [comment]
Your question is off topic. Please only raise issues related to this code. I am not the developer of the code you mention.

**Comment by lakromah** [comment]
My apologies

I realised that after sending the message.

Sorry for wasting your time
Kind regards
Linda Akromah
